### ISSUE TITLE
Problem with init

### ISSUE THREAD

**Issue by carminelau** [avaldebe/PMserial#30]
Hi I made the init and after a few seconds about 10 I'm going to make the first reading. The problem is that sometimes the reading of the three Particulate values ​​is 0.

**Comment by avaldebe** [comment]
What sensor model are you using?
Maybe you could check your senor wiring using a USB serial adaptor and my Python library [PyPMS]?

[PyPMS]: https://avaldebe.github.io/PyPMS/

**Comment by avaldebe** [comment]
Hi @carminelau 

It is close to a year since you open this issue, and you have not answered my follow up questions. Without that info I can not help you to debug your problem:

I hope you managed to find the problem since, so I'll close the issue.
Please re-open it if this was not the case.
